# Generated by Django 2.2 on 2020-09-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('opened', 'opened'), ('closed', 'closed'), ('suspended', 'suspended'), ('deleted', 'deleted')], default='pending', max_length=100)),
            ],
        ),
    ]
